/* Obsidian Capital — job dataset. Single source of truth for all pages. */

const JOBS = [
  /* ------------------------------ Engineering ------------------------------ */
  {
    id: "eng-backend-senior",
    title: "Senior Backend Engineer — Core Banking",
    department: "Engineering",
    location: "New York",
    type: "Full-time",
    seniority: "Senior",
    salary: "$190,000 – $260,000",
    summary:
      "Own the services that move billions in client capital every day. You will design low-latency, fault-tolerant systems at the heart of Obsidian's core banking platform.",
    responsibilities: [
      "Design and operate distributed services processing high-value transactions with strict consistency guarantees",
      "Lead architecture reviews and drive technical direction across the core banking group",
      "Partner with risk and compliance engineering to keep systems audit-ready by construction",
      "Mentor engineers and raise the bar on code quality, testing, and operational excellence",
    ],
    requirements: [
      "7+ years building backend systems in Java, Go, or C++ at scale",
      "Deep understanding of distributed systems, consensus, and transactional integrity",
      "Experience operating regulated or high-stakes production environments",
      "A pragmatic, ownership-driven approach to engineering",
    ],
    posted: "2026-06-18",
  },
  {
    id: "eng-frontend",
    title: "Frontend Engineer — Client Platforms",
    department: "Engineering",
    location: "London",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "£85,000 – £120,000",
    summary:
      "Craft the interfaces our private clients and institutional partners use to see and move their wealth. Precision, polish, and performance are the brief.",
    responsibilities: [
      "Build rich, accessible web experiences for Obsidian's client-facing platforms",
      "Translate design language into a reusable, meticulously documented component system",
      "Instrument and optimise for real-user performance across global markets",
      "Collaborate daily with design, product, and backend teams",
    ],
    requirements: [
      "3+ years of modern JavaScript/TypeScript experience",
      "A sharp eye for typography, motion, and interaction detail",
      "Experience with accessibility standards (WCAG) and performance profiling",
      "Portfolio or examples of interface work you are proud of",
    ],
    posted: "2026-06-22",
  },
  {
    id: "eng-sre",
    title: "Site Reliability Engineer",
    department: "Engineering",
    location: "Zurich",
    type: "Full-time",
    seniority: "Senior",
    salary: "CHF 160,000 – 210,000",
    summary:
      "Keep a global bank online. You will engineer the reliability, observability, and incident response practice for platforms where downtime is measured in headlines.",
    responsibilities: [
      "Define and defend SLOs for tier-zero trading and banking services",
      "Build automation that eliminates toil across deployment, failover, and recovery",
      "Lead blameless post-incident reviews and drive systemic fixes",
      "Design chaos and resilience testing programmes",
    ],
    requirements: [
      "5+ years in SRE, production engineering, or infrastructure roles",
      "Fluency with Kubernetes, infrastructure-as-code, and observability stacks",
      "Calm, structured decision-making under incident pressure",
      "Experience in financial services is a plus, not a prerequisite",
    ],
    posted: "2026-06-10",
  },
  {
    id: "eng-security",
    title: "Security Engineer — Threat Detection",
    department: "Engineering",
    location: "New York",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "$165,000 – $220,000",
    summary:
      "Defend one of the world's most targeted institutions. Build detection pipelines and hunt adversaries across a global estate.",
    responsibilities: [
      "Develop and tune detection logic across network, endpoint, and cloud telemetry",
      "Automate triage and response workflows for the 24/7 security operations centre",
      "Run threat-hunting campaigns against realistic adversary models",
      "Work with red team to close gaps found in purple-team exercises",
    ],
    requirements: [
      "4+ years in security engineering, detection, or incident response",
      "Strong scripting ability (Python preferred) and query-language fluency",
      "Understanding of attacker tradecraft and the MITRE ATT&CK framework",
      "Relevant certifications welcome but never required",
    ],
    posted: "2026-06-25",
  },
  {
    id: "eng-data",
    title: "Data Engineer — Analytics Platform",
    department: "Engineering",
    location: "Singapore",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "S$140,000 – S$190,000",
    summary:
      "Build the pipelines that turn petabytes of market and client data into the firm's decision-making edge.",
    responsibilities: [
      "Design batch and streaming pipelines feeding research, risk, and reporting",
      "Own data quality, lineage, and governance tooling",
      "Optimise warehouse performance and cost across cloud regions",
      "Partner with quant researchers on high-throughput data delivery",
    ],
    requirements: [
      "3+ years with Spark, Flink, or similar large-scale data frameworks",
      "Strong SQL and one of Python/Scala/Java",
      "Experience with orchestration tools and data contract patterns",
      "Care for correctness — our numbers move markets",
    ],
    posted: "2026-06-15",
  },
  {
    id: "eng-ml",
    title: "Machine Learning Engineer — Fraud Intelligence",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    seniority: "Senior",
    salary: "$185,000 – $250,000",
    summary:
      "Ship models that stop fraud in the milliseconds between intent and settlement, protecting clients without adding friction.",
    responsibilities: [
      "Train, deploy, and monitor real-time fraud detection models",
      "Build feature platforms serving sub-10ms inference at scale",
      "Design evaluation frameworks resilient to adversarial drift",
      "Collaborate with financial-crime investigators to encode domain insight",
    ],
    requirements: [
      "5+ years of applied ML in production environments",
      "Strong grounding in anomaly detection and imbalanced classification",
      "Production MLOps experience: serving, monitoring, retraining loops",
      "Ability to explain model decisions to regulators and auditors",
    ],
    posted: "2026-06-28",
  },
  {
    id: "eng-platform-lead",
    title: "Engineering Lead — Developer Platform",
    department: "Engineering",
    location: "London",
    type: "Full-time",
    seniority: "Lead",
    salary: "£150,000 – £200,000",
    summary:
      "Lead the team that makes two thousand engineers faster. Own the build, CI/CD, and internal tooling estate for the entire firm.",
    responsibilities: [
      "Set the technical vision for Obsidian's internal developer platform",
      "Manage and grow a team of 8–10 platform engineers",
      "Drive adoption through developer experience, not mandate",
      "Report platform health and productivity metrics to the CTO office",
    ],
    requirements: [
      "8+ years of engineering with 2+ years leading teams",
      "Track record building platform or infrastructure products",
      "Strong opinions, loosely held, about developer productivity",
      "Empathy for engineers as your customers",
    ],
    posted: "2026-06-05",
  },

  /* ------------------------------ Quantitative ----------------------------- */
  {
    id: "quant-researcher",
    title: "Quantitative Researcher — Systematic Strategies",
    department: "Quantitative",
    location: "New York",
    type: "Full-time",
    seniority: "Senior",
    salary: "$250,000 – $400,000",
    summary:
      "Find signal where others see noise. Research and productionise systematic strategies across global asset classes.",
    responsibilities: [
      "Develop alpha models from idea through backtest to live trading",
      "Analyse vast alternative and market datasets for persistent signal",
      "Collaborate with quant developers on research infrastructure",
      "Present findings to the strategy committee with statistical rigour",
    ],
    requirements: [
      "PhD or MSc in mathematics, physics, statistics, or computer science",
      "Demonstrated research ability — publications or live track record",
      "Expert-level Python and numerical computing",
      "Intellectual honesty about what the data does and does not say",
    ],
    posted: "2026-06-20",
  },
  {
    id: "quant-dev",
    title: "Quantitative Developer — Pricing Engines",
    department: "Quantitative",
    location: "London",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "£120,000 – £170,000",
    summary:
      "Turn mathematics into microseconds. Build the pricing and risk engines behind Obsidian's derivatives franchise.",
    responsibilities: [
      "Implement pricing models for exotic and vanilla derivatives in C++",
      "Optimise numerical libraries for latency and throughput",
      "Build tooling that lets traders trust and interrogate model output",
      "Validate implementations against independent model review",
    ],
    requirements: [
      "Strong C++ (17/20) and solid Python",
      "Grounding in stochastic calculus and numerical methods",
      "Experience with derivatives pricing or risk systems preferred",
      "Degree in a quantitative discipline",
    ],
    posted: "2026-06-12",
  },
  {
    id: "quant-risk",
    title: "Risk Analyst — Market Risk",
    department: "Quantitative",
    location: "Zurich",
    type: "Full-time",
    seniority: "Junior",
    salary: "CHF 110,000 – 140,000",
    summary:
      "Quantify what could go wrong before it does. Join the market risk team overseeing the firm's global trading book.",
    responsibilities: [
      "Produce and interpret daily VaR, stress, and scenario analyses",
      "Investigate limit breaches and escalate with clear narrative",
      "Improve risk models and automate reporting workflows",
      "Engage with traders to understand and challenge positions",
    ],
    requirements: [
      "1–3 years in risk, trading, or a quantitative graduate role",
      "Solid statistics and comfort with Python or R",
      "Ability to explain complex risk simply to senior stakeholders",
      "FRM/CFA progress viewed favourably",
    ],
    posted: "2026-06-26",
  },

  /* ---------------------------- Trading & Markets --------------------------- */
  {
    id: "markets-lowlatency",
    title: "Low-Latency Systems Engineer — Electronic Trading",
    department: "Trading & Markets",
    location: "New York",
    type: "Full-time",
    seniority: "Senior",
    salary: "$220,000 – $320,000",
    summary:
      "Compete at the speed of light. Engineer the execution systems where nanoseconds decide outcomes.",
    responsibilities: [
      "Profile and optimise the hot path of our execution engines",
      "Work with kernel-bypass networking, FPGA teams, and exchange connectivity",
      "Design lock-free data structures and mechanical-sympathy architectures",
      "Measure everything; assume nothing",
    ],
    requirements: [
      "Expert C++ with deep understanding of CPU architecture and memory models",
      "Experience in low-latency trading, HFT, or comparable systems",
      "Familiarity with market microstructure and exchange protocols",
      "Obsession with measurement over intuition",
    ],
    posted: "2026-06-08",
  },
  {
    id: "markets-sales-trader",
    title: "Sales Trader — Equities",
    department: "Trading & Markets",
    location: "Singapore",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "S$180,000 – S$260,000 + bonus",
    summary:
      "Be the voice our institutional clients trust in fast markets. Execute with judgment, colour, and discretion across APAC equities.",
    responsibilities: [
      "Manage execution and market colour for institutional client orders",
      "Build durable relationships with portfolio managers and dealing desks",
      "Coordinate with research and structuring to deliver firm-wide value",
      "Uphold best-execution and conduct standards without exception",
    ],
    requirements: [
      "3+ years on a sales trading or execution desk",
      "Relevant regulatory licences (or ability to obtain swiftly)",
      "Composure and clarity under market stress",
      "Fluent English; Mandarin a strong plus",
    ],
    posted: "2026-06-17",
  },
  {
    id: "markets-structurer",
    title: "Structured Products Specialist",
    department: "Trading & Markets",
    location: "Zurich",
    type: "Full-time",
    seniority: "Senior",
    salary: "CHF 180,000 – 250,000 + bonus",
    summary:
      "Design bespoke investment solutions for the world's most sophisticated private clients and family offices.",
    responsibilities: [
      "Structure notes and derivative solutions tailored to client objectives",
      "Work with trading desks on pricing, hedging, and lifecycle management",
      "Draft term sheets and ensure documentation accuracy with legal",
      "Educate advisors on product mechanics and suitability",
    ],
    requirements: [
      "5+ years in structuring, derivatives sales, or product engineering",
      "Strong grasp of options theory and cross-asset payoffs",
      "Meticulous documentation habits",
      "German and English fluency preferred",
    ],
    posted: "2026-06-03",
  },

  /* -------------------------------- Corporate ------------------------------- */
  {
    id: "corp-hr-partner",
    title: "Senior HR Business Partner",
    department: "Corporate",
    location: "London",
    type: "Full-time",
    seniority: "Senior",
    salary: "£95,000 – £130,000",
    summary:
      "Shape how a modern bank grows its people. Partner with engineering and markets leadership on everything from talent strategy to hard conversations.",
    responsibilities: [
      "Advise senior leaders on organisation design, performance, and retention",
      "Lead talent reviews, succession planning, and compensation cycles",
      "Coach managers through complex employee-relations matters",
      "Use people data to inform, not decorate, decisions",
    ],
    requirements: [
      "6+ years of HRBP experience, ideally in finance or technology",
      "Sound judgment on employment-law adjacent matters",
      "Credibility with demanding, analytical stakeholders",
      "Discretion as a default setting",
    ],
    posted: "2026-06-21",
  },
  {
    id: "corp-legal-counsel",
    title: "Legal Counsel — Markets Regulation",
    department: "Corporate",
    location: "New York",
    type: "Full-time",
    seniority: "Senior",
    salary: "$210,000 – $290,000",
    summary:
      "Navigate the regulatory frontier of global markets. Advise trading and product teams before questions become problems.",
    responsibilities: [
      "Counsel desks on securities, derivatives, and market-conduct regulation",
      "Manage regulatory inquiries and examinations end-to-end",
      "Review new products and business initiatives for legal risk",
      "Track and translate rulemaking into practical guidance",
    ],
    requirements: [
      "JD with 5+ years at a top firm or in-house financial institution",
      "Deep familiarity with SEC/CFTC/FINRA frameworks",
      "Bar admission in New York",
      "Clear, commercial written advice",
    ],
    posted: "2026-06-14",
  },
  {
    id: "corp-finance-analyst",
    title: "Financial Analyst — Group Finance",
    department: "Corporate",
    location: "London",
    type: "Full-time",
    seniority: "Junior",
    salary: "£55,000 – £72,000",
    summary:
      "Learn how a bank actually works from the inside. Support planning, forecasting, and management reporting for the group.",
    responsibilities: [
      "Build and maintain forecasting models for business units",
      "Prepare monthly management reporting packs for the executive committee",
      "Analyse variances and tell the story behind the numbers",
      "Support annual budgeting and strategic planning cycles",
    ],
    requirements: [
      "1–3 years in FP&A, audit, or transaction services",
      "Advanced Excel; SQL or Python a plus",
      "Studying towards ACA/CIMA/CFA welcomed and funded",
      "Precision and curiosity in equal measure",
    ],
    posted: "2026-06-27",
  },
  {
    id: "corp-exec-assistant",
    title: "Executive Assistant to the CTO",
    department: "Corporate",
    location: "New York",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "$95,000 – $125,000",
    summary:
      "Run the operating system of the technology executive office. Calendar, priorities, people — you make the complex look effortless.",
    responsibilities: [
      "Own complex global scheduling, travel, and meeting logistics",
      "Prepare briefings and manage follow-ups from leadership meetings",
      "Act as a trusted gatekeeper and culture-carrier for the office",
      "Coordinate offsites, town halls, and executive visits",
    ],
    requirements: [
      "4+ years supporting C-level executives in a fast-paced environment",
      "Impeccable discretion, judgment, and written communication",
      "Mastery of modern productivity tooling",
      "Grace under relentless pressure",
    ],
    posted: "2026-06-23",
  },
  {
    id: "corp-comms",
    title: "Communications Manager — Brand & Media",
    department: "Corporate",
    location: "London",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "£70,000 – £95,000",
    summary:
      "Tell the story of a 150-year-old institution reinventing itself in public. Own media relations and executive communications.",
    responsibilities: [
      "Manage press relationships and coordinate responses to media inquiries",
      "Draft executive speeches, op-eds, and internal announcements",
      "Shape narrative for product launches and firm milestones",
      "Monitor sentiment and advise leadership on communications risk",
    ],
    requirements: [
      "4+ years in corporate communications, journalism, or agency PR",
      "Exceptional writing under deadline",
      "Experience handling sensitive or regulated communications",
      "Calm counsel when headlines get loud",
    ],
    posted: "2026-06-09",
  },
  {
    id: "corp-workplace-experience",
    title: "Workplace Experience Coordinator",
    department: "Corporate",
    location: "Singapore",
    type: "Full-time",
    seniority: "Junior",
    salary: "S$55,000 – S$70,000",
    summary:
      "Make our Singapore office the best place anyone on the team has ever worked. Events, amenities, and the thousand small details of a great workplace.",
    responsibilities: [
      "Plan and execute office events, from town halls to client receptions",
      "Manage vendor relationships for catering, amenities, and supplies",
      "Own the front-of-house experience for employees and guests",
      "Gather feedback and continuously improve workplace services",
    ],
    requirements: [
      "1–3 years in hospitality, events, or workplace/office management",
      "Warm, proactive, unflappable",
      "Strong organisational and budgeting skills",
      "Fluent English; additional languages valued",
    ],
    posted: "2026-06-24",
  },

  /* ------------------------------- Internships ------------------------------ */
  {
    id: "intern-swe",
    title: "Software Engineering Intern — Summer 2027",
    department: "Internships",
    location: "New York",
    type: "Internship",
    seniority: "Intern",
    salary: "$12,000 / month",
    summary:
      "Ten weeks. Real systems. Real ownership. Ship production code alongside some of the best engineers in finance.",
    responsibilities: [
      "Deliver a scoped project on a live engineering team",
      "Participate in code review, design discussion, and incident learning",
      "Present your work to senior technology leadership",
      "Pair with a dedicated mentor throughout the programme",
    ],
    requirements: [
      "Penultimate-year student in CS or a related field",
      "Solid programming fundamentals in any language",
      "Evidence of building things — coursework, open source, side projects",
      "Curiosity about how money actually moves",
    ],
    posted: "2026-06-30",
  },
  {
    id: "intern-quant",
    title: "Quantitative Research Intern — Summer 2027",
    department: "Internships",
    location: "London",
    type: "Internship",
    seniority: "Intern",
    salary: "£9,500 / month",
    summary:
      "Test your mathematics against live markets. Work on a genuine research question with our systematic strategies group.",
    responsibilities: [
      "Own a research project from hypothesis to presented findings",
      "Work with production research infrastructure and real datasets",
      "Attend research seminars and desk shadowing sessions",
      "Present conclusions to the quant research leadership",
    ],
    requirements: [
      "Advanced degree in progress: mathematics, physics, statistics, or CS",
      "Strong probability, statistics, and Python",
      "Prior research experience of any kind",
      "Comfort being wrong quickly and often",
    ],
    posted: "2026-06-30",
  },
  {
    id: "intern-ops",
    title: "Operations Intern — Summer 2027",
    department: "Internships",
    location: "Zurich",
    type: "Internship",
    seniority: "Intern",
    salary: "CHF 5,500 / month",
    summary:
      "See how a global bank runs beneath the surface. Rotate through settlements, client onboarding, and process engineering.",
    responsibilities: [
      "Support daily operations across two rotation placements",
      "Map a process end-to-end and propose measurable improvements",
      "Shadow senior operations managers and control functions",
      "Deliver a capstone improvement project",
    ],
    requirements: [
      "Undergraduate student, any discipline",
      "Analytical mindset and attention to detail",
      "Interest in how financial infrastructure works",
      "German helpful, not required",
    ],
    posted: "2026-06-29",
  },
  {
    id: "intern-marketing",
    title: "Marketing & Brand Intern — Summer 2027",
    department: "Internships",
    location: "London",
    type: "Internship",
    seniority: "Intern",
    salary: "£3,800 / month",
    summary:
      "Help a heritage brand speak to a new generation. Work across campaigns, content, and events with the brand team.",
    responsibilities: [
      "Assist in planning and executing brand campaigns and events",
      "Draft content for internal and external channels",
      "Analyse campaign performance and compile insight reports",
      "Contribute ideas — the best one last summer shipped globally",
    ],
    requirements: [
      "Undergraduate student in marketing, communications, or similar",
      "Sharp writing and an eye for visual craft",
      "Basic analytics familiarity (or eagerness to learn)",
      "A portfolio of anything you've made — school counts",
    ],
    posted: "2026-06-29",
  },

  /* --------------------------- Facilities & Services ------------------------ */
  {
    id: "fac-cleaning-operative",
    title: "Cleaning Operative — Evening Shift",
    department: "Facilities & Services",
    location: "London",
    type: "Part-time",
    seniority: "Entry-level",
    salary: "£16.50 / hour + benefits",
    summary:
      "Keep a landmark headquarters immaculate. Join the in-house team that takes visible pride in a building the whole firm is proud of.",
    responsibilities: [
      "Clean and maintain office floors, meeting suites, and common areas",
      "Follow health, safety, and secure-area protocols",
      "Report maintenance issues through the facilities system",
      "Work as part of a supportive, long-tenured evening team",
    ],
    requirements: [
      "Previous cleaning experience helpful but not required — we train",
      "Reliability and pride in a job well done",
      "Ability to pass building security screening",
      "Right to work in the UK",
    ],
    posted: "2026-06-26",
  },
  {
    id: "fac-coordinator",
    title: "Facilities Coordinator",
    department: "Facilities & Services",
    location: "New York",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "$68,000 – $85,000",
    summary:
      "Run the day-to-day heartbeat of our Manhattan headquarters — maintenance, vendors, moves, and everything in between.",
    responsibilities: [
      "Coordinate preventative maintenance and rapid-response repairs",
      "Manage vendor scheduling, access, and quality of work",
      "Support office moves, space planning, and desk allocations",
      "Maintain compliance records for building safety systems",
    ],
    requirements: [
      "2+ years in facilities, property, or building operations",
      "Strong coordination skills across contractors and stakeholders",
      "Familiarity with CMMS/ticketing systems",
      "Calm problem-solving when things break at 8:55am",
    ],
    posted: "2026-06-19",
  },
  {
    id: "fac-security-officer",
    title: "Corporate Security Officer",
    department: "Facilities & Services",
    location: "New York",
    type: "Full-time",
    seniority: "Entry-level",
    salary: "$52,000 – $64,000",
    summary:
      "Be the first impression and the last line. Protect people, premises, and reputation at our global headquarters.",
    responsibilities: [
      "Manage lobby access, visitor screening, and credential checks",
      "Conduct patrols and monitor surveillance and alarm systems",
      "Respond to incidents following established protocols",
      "Liaise with building management and local authorities",
    ],
    requirements: [
      "Valid security licence (or ability to obtain before start)",
      "Professional presence and excellent judgment",
      "Clear communication in high-pressure moments",
      "Prior corporate, military, or law-enforcement experience a plus",
    ],
    posted: "2026-06-16",
  },
  {
    id: "fac-catering",
    title: "Catering Assistant — Executive Dining",
    department: "Facilities & Services",
    location: "Zurich",
    type: "Full-time",
    seniority: "Entry-level",
    salary: "CHF 55,000 – 62,000",
    summary:
      "Deliver five-star hospitality inside a private bank. Support the executive dining and client-event kitchens.",
    responsibilities: [
      "Assist chefs with service for client lunches and executive events",
      "Maintain immaculate presentation and hygiene standards",
      "Set up and reset private dining rooms",
      "Handle discreet service for confidential meetings",
    ],
    requirements: [
      "Experience in hospitality, restaurant, or catering service",
      "Polish, discretion, and attention to detail",
      "Food-hygiene certification (or willingness to obtain)",
      "German or French conversational ability preferred",
    ],
    posted: "2026-06-11",
  },
  {
    id: "fac-mailroom",
    title: "Mailroom & Logistics Assistant",
    department: "Facilities & Services",
    location: "London",
    type: "Full-time",
    seniority: "Entry-level",
    salary: "£28,000 – £33,000",
    summary:
      "Keep documents, deliveries, and equipment moving through a building where 'sensitive' is the default classification.",
    responsibilities: [
      "Sort, track, and deliver internal and external mail securely",
      "Manage courier bookings and receipt of high-value deliveries",
      "Support secure document destruction workflows",
      "Assist facilities with equipment moves and stock management",
    ],
    requirements: [
      "Organised, punctual, and trustworthy",
      "Comfortable with tracking systems and handheld scanners",
      "Physically comfortable with an active, on-your-feet role",
      "Previous mailroom or logistics experience a bonus",
    ],
    posted: "2026-06-13",
  },
  {
    id: "fac-cleaning-supervisor",
    title: "Cleaning Services Supervisor",
    department: "Facilities & Services",
    location: "Singapore",
    type: "Full-time",
    seniority: "Mid-level",
    salary: "S$48,000 – S$58,000",
    summary:
      "Lead the team that keeps our Singapore office spotless. Quality, scheduling, and people leadership for a crew of twelve.",
    responsibilities: [
      "Supervise daily cleaning operations and quality inspections",
      "Manage shift rosters, training, and supply inventory",
      "Coordinate deep-clean schedules around business operations",
      "Champion safety standards and sustainable cleaning practices",
    ],
    requirements: [
      "3+ years in cleaning or facilities services, 1+ supervising",
      "Fair, motivating leadership style",
      "Basic reporting and budgeting comfort",
      "Knowledge of green cleaning standards a plus",
    ],
    posted: "2026-06-07",
  },
  {
    id: "fac-reception",
    title: "Corporate Receptionist — Client Floor",
    department: "Facilities & Services",
    location: "Zurich",
    type: "Full-time",
    seniority: "Entry-level",
    salary: "CHF 62,000 – 72,000",
    summary:
      "Welcome billionaires, regulators, and graduates with the same impeccable warmth. Front-of-house for our private client floor.",
    responsibilities: [
      "Greet and register clients and visitors with five-star courtesy",
      "Manage meeting-room bookings, refreshments, and AV readiness",
      "Coordinate with security on visitor access",
      "Handle switchboard and correspondence for the client floor",
    ],
    requirements: [
      "Experience in luxury hospitality, aviation, or corporate reception",
      "Immaculate presentation and discretion",
      "Fluent German and English; French a plus",
      "Unshakeable composure",
    ],
    posted: "2026-06-04",
  },
  {
    id: "eng-intern-apprentice",
    title: "Technology Apprentice — Degree Programme",
    department: "Internships",
    location: "London",
    type: "Apprenticeship",
    seniority: "Entry-level",
    salary: "£28,000 + funded degree",
    summary:
      "Earn a software engineering degree while working inside a global bank — fully funded, four years, no student debt.",
    responsibilities: [
      "Rotate across engineering teams while studying part-time",
      "Build real features under mentorship from day one",
      "Complete accredited coursework toward a BSc in Digital & Technology Solutions",
      "Grow into a full engineering role on graduation",
    ],
    requirements: [
      "A-levels (or equivalent) including strong maths results",
      "Genuine enthusiasm for programming — show us anything you've built",
      "No university degree required — that's the point",
      "Right to work in the UK for the programme duration",
    ],
    posted: "2026-06-30",
  },
];

/* Derived lists used by filter UIs */
const DEPARTMENTS = [...new Set(JOBS.map((j) => j.department))];
const LOCATIONS = [...new Set(JOBS.map((j) => j.location))];
const TYPES = [...new Set(JOBS.map((j) => j.type))];
const SENIORITIES = [...new Set(JOBS.map((j) => j.seniority))];
